### ISSUE TITLE
Can't cd to /input

### ISSUE THREAD

**Issue by burkesquires** [hexylena/docker-circos#1]
Thank you for putting this together but I am running into an issue:

/entrypoint.sh: cd: line 2: can't cd to /input

**Comment by hexylena** [comment]
Hi @burkesquires that will occur if you haven't mounted a volume containing a circos configuration file to build.

E.g. in readme `docker run -it -v $(pwd)/example:/input erasche/circos:latest -conf /input/circos.conf`

**Comment by burkesquires** [comment]
Oh drats! Thanks for the help! Sorry to trouble you!

**Comment by hexylena** [comment]
No worries, glad it was something easy to solve :)
